// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID          uint      `json:"id"`
	UserID      uint      `json:"user_id"`
	HashedToken string    `json:"hashed_token"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type User struct {
	ID             uint      `json:"id"`
	Uuid           uuid.UUID `json:"uuid"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
